// <auto-generated />
namespace PropertyDealer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddedCustomermodeland1tomannyrelationtoaddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedCustomermodeland1tomannyrelationtoaddress));
        
        string IMigrationMetadata.Id
        {
            get { return "202004152220432_Added Customer model and 1 to manny relation to address"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
