// <auto-generated />
namespace PropertyDealer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _1tomanylinkforaddressmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1tomanylinkforaddressmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202004150906222_1 to many link for address model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
